apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
#  storageClassName: "gluster"
  volumeName: prometheus-pv
